NSIS_SCRIPT pre-patch
Remove -OPT:NOWIN98 flag
Drop -WX option
Workaround error C2220: warning treated as error
Since warning C4456: declaration of '&1' hides previous local declaration introduced by NSIS_SCRIPT
Silent warning C4566 character represented by universal-character-name 'char' cannot be represented in the current code page (page). introduced by VC-LTL at ucrt/*/stdlib.h making console output terrible without this. define _DISABLE_DEPRECATE_LTL_MESSAGE supresses note message provided by VC-LTL.